### ISSUE TITLE
Framework references

### ISSUE THREAD

**Issue by felixSchl** [OmniSharp/omnisharp-server#101]
This is more a question than a issue, I suppose:

If I create a vanilla gtksharp project using monodevelop and then switch over to vim to write some code, I get told that Gtk is a unknown reference. Is there any way to make it understand these non-path-to-dll references?

**Comment by Asdas91** [comment]
Hi nosami, could you (or anyone) give me some hints on how to use local reference? Or maybe hack it in the code, however I do not think I am good enough with C#.  I would greatly appreciate it as I am working on a school project using GTK. It would be more comfortable if I could use autocompletion and if the code checker did not mark anything GTK related as an error. It builds just fine though

BTW this project is great and I am very happy that I can program in C# using Vim.

**Comment by mzavoloka** [comment]
I know that this project is no longer supported and superseded by omnisharp-roslyn. But I was unable to install roslyn and decided to stick with this project for a bit. At least it's mature enough.

So, I want to add few words.

This repo have changed from the moment of @nosami's reply. And now the link
> https://github.com/nosami/OmniSharpServer/blob/master/OmniSharp/Solution/CSharpProject.cs#L17

leads to empty line. At the time when @nosami's posted his reply, his link were leading to https://github.com/OmniSharp/omnisharp-server/blob/dde56825ae0b0d1335e0d110a20be35650c02301/OmniSharp/Solution/CSharpProject.cs#L17
So this is the line that @nosami posted about.

But at the current moment AssemblySearchPaths were renamed and moved to another file. Here's the link to this variable that you may want to hack:
https://github.com/OmniSharp/omnisharp-server/blob/e1902915c6790bcec00b8d551199c8a3537d33c9/OmniSharp/Solution/AssemblySearch.cs#L5
Note that this is the link to the current state of the file - 2016 Jan 12 (this variable may be moved or renamed in the future again). If this variable will be changed again, just search for "program files" in the repo and most probably you'll find it.

Now, here's an example of how I hacked it. I use omnisharp-vim. So, I added following paths to the variable in the file ~/.vim/bundle/omnisharp-vim/server/OmniSharp/Solution/AssemblySearch.cs on my machine:
```@"/usr/lib/cli",
@"/usr/lib/cli/atk-sharp-3.0",
@"/usr/lib/cli/gdk-sharp-3.0",
@"/usr/lib/cli/gtk-sharp-3.0",
@"/usr/lib/cli/glib-sharp-3.0",
@"/usr/lib/cli/pango-sharp-3.0",
@"/usr/lib/cli/gio-sharp-3.0",
@"/opt/monodevelop/lib/mono",
@"/opt/monodevelop/lib/mono/gtk-sharp-2.0",
```

I got these from Monodevelop's vanilla Gtk# project.
Then I rebuilded Omnisharp server by running `xbuild` command in the dir ~/.vim/bundle/omnisharp-vim/server/OmniSharp. Ensure that you've killed all the processes of Omnisharp server before going further. Then I reinstalled omnisharp-vim plugin by running `:PluginInstall` in vim (this is Vundle's command). That's it.

Now syntax check and completion is working, but, unfortunately, building fails with no errors. Idk why. At the moment I have to build project from Monodevelop.
