### ISSUE TITLE
scriptcs support!

### ISSUE THREAD

**Issue by glennblock** [OmniSharp/omnisharp-server#120]
Add support for using OmniSharpServer with scriptcs for intellisense, etc.

**Comment by samuba** [comment]
+1

**Comment by nosami** [comment]
It's happening - https://github.com/filipw/omnisharp-roslyn/compare/feature/scriptcs :)

**Comment by glennblock** [comment]
Yep Filip is on it!

**Comment by sayedihashimi** [comment]
This is great news 📰, can't wait to try it out.

**Comment by bitbonk** [comment]
+1 +1

**Comment by samuba** [comment]
I asked Filip on a status for this and he replied it is planned to be PR in the next 2 weeks

**Comment by filipw** [comment]
just rebased and pushed an bunch of changes if anyone's interested https://github.com/filipw/omnisharp-roslyn/commits/feature/scriptcs

**Comment by filipw** [comment]
let's close this

**Comment by sayedihashimi** [comment]
Closing per @filipw
