### ISSUE TITLE
Not able to ignore specific code warnings on Sublime

### ISSUE THREAD

**Issue by luispedrofonseca** [OmniSharp/omnisharp-server#135]

**Comment by aMoniker** [comment]
This isn't working for me. I've got the rule `".*Name should have prefix '_'.*"` added to `IgnoredCodeIssues` in my custom config.json which `omnisharp_server_config_location` is pointing to. As a sanity check, adding the same thing to the built-in config.json doesn't work either.

Also, when I quit sublime, restart, and open a C# file, I get `OmniSharp: Error talking to <server>`.

**Comment by aMoniker** [comment]
Ah, scratch that. I've got the config.json working now. Still getting intermittent errors talking to the server on ST restarts though.
