### ISSUE TITLE
SLN file searching problems for Unity3D projects

### ISSUE THREAD

**Issue by bro-santana** [OmniSharp/omnisharp-server#144]
The SLN search stops at the first SLN file. That causes an issue with Unity3D. Unity gerates 2 SLN files "FolderName.sln" and "FolderName-csharp.sln". When it tries the former the assemblies are not loaded. When I delete the former and omnisharp finds the latter , everything works as charm.

**Comment by sonoshee-desu** [comment]
What about Sublime Text? I have an issue and I'm afraid it has to do with this. Basically Unity creates the two .sln files cited above, however Omnisharp can't detect the 2008 version of the .sln, only the 2015 version generated by Unity through Visual Studio. Is there anything I can do?
