### ISSUE TITLE
Mscorlib not found

### ISSUE THREAD

**Issue by davidpodhola** [OmniSharp/omnisharp-server#192]
When starting server `mscorlib not found exception` is reported see the attached screenshot.

![mscorlib not found](http://s4.postimg.org/a9q2nfix9/omnibug.png)

**Comment by nosami** [comment]
Which version of Windows / .net are you running?

Take a look here https://github.com/OmniSharp/omnisharp-server/blob/6785380ca55c4645b48b66d1c1b3466a0a5fcd5e/OmniSharp/Solution/AssemblySearch.cs#L8-L32

**Comment by davidpodhola** [comment]
`ver` reports `Microsoft Windows [Version 6.3.9600]`, it is Windows 8.1 Enterprise 32 bit.
`Release` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full` has value `379893` meaning `.NET Framework 4.5.2`.

Thanks for pointing to the list, it is clear now. My `mscorlib.dll` is in `C:\Windows\Microsoft.NET\Framework\v4.0.30319` probably because I do not have either SDK or Visual Studio installed. I assume it is a valid location. Will change, test and submit PR if it works. Very cool, thank you!

**Comment by davidpodhola** [comment]
Works for me now (manually copied the `bin` content to `C:\Users\david.podhola\.atom\packages\omnisharp-atom\node_modules\omnisharp-server-binaries\lib\server`)

**Comment by koenmetsu** [comment]
Not sure if this is related, but I'm getting a lot of issues on mscorlib with nuget packages.

>You must add a reference to assembly 'mscorlib'

![2015-07-08_1447](https://cloud.githubusercontent.com/assets/1169539/8570414/5823ee54-2580-11e5-8ff7-4840d4d49ce8.png)

Specifics:
Class library project, .NET Framework 4.5, on a Win 7 Enterprise 64bit.
Atom 1.0.2, Omnisharp 0.20.

The folder suggested by @davidpodhola (.atom\packages\omnisharp-atom\node_modules\omnisharp-server-binaries\lib\server) does not seem to exist on my machine.

Any ideas?
