### ISSUE TITLE
Lots of mscorlib issues with 3rd party packages

### ISSUE THREAD

**Issue by koenmetsu** [OmniSharp/omnisharp-server#204]
Hi

I'm getting a lot of mscorlib issues with 3rd party nuget packages, any idea how to fix these?

![2015-07-10_1429](https://cloud.githubusercontent.com/assets/1169539/8618637/474380ea-2710-11e5-9ca3-7c93d73e1e00.png)

![2015-07-10_1430](https://cloud.githubusercontent.com/assets/1169539/8618636/4741cd86-2710-11e5-8619-d7b1e255c761.png)

Running on Windows 7.1, targeting .net 4.5.2, Atom 1.0.2, omnisharp-atom 0.19.1.

**Comment by nosami** [comment]
I moved your issue here https://github.com/OmniSharp/omnisharp-roslyn/issues/265

**Comment by koenmetsu** [comment]
Thanks

**Comment by nosami** [comment]
Fixed in omnisharp-roslyn v1.4.1
