### ISSUE TITLE
"Build failed" but successful, no errors

### ISSUE THREAD

**Issue by doxkb** [OmniSharp/omnisharp-server#205]
When I build a project with omnisharp, I get "Build failed" message in vim and no error in the server console. However, the build is successful. 

I debugged the server and I get null in e.Data in OutputDataReceived(object sender, DataReceivedEventArgs e) in BuildHandler.cs

I get no output at all when I build the solution with the same arguments from the command line.

On Windows 7 with VS2013 installed.

**Comment by nosami** [comment]
Try using the async build command instead. This project is no longer supported.
