### ISSUE TITLE
https://github.com/dotnet/vscode-dotnetcore will also help minimize the downloader dependency download duration/size as well.

### ISSUE THREAD

**Issue by c06645232f8919554d4df3c88e101e38** [OmniSharp/omnisharp-server#227]
https://github.com/dotnet/vscode-dotnetcore will also help minimize the downloader dependency download duration/size as well.

_Originally posted by @NTaylorMullen in https://github.com/OmniSharp/omnisharp-vscode/issues/3517#issuecomment-576851037_

**Comment by NTaylorMullen** [comment]
Confused what this migration piece is. Anyone care to shed some light?
